name: ferry_tracking
description: ferry tracking.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  flutter_mjpeg: ^2.0.0
  firebase_core: ^1.3.0
  cloud_firestore: ^2.3.0
  location: ^4.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

